name: Build Landscape from LFX

on:
  workflow_dispatch:
  schedule:
  - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: jmertic/lfx-landscape-tools@e4e3da3271d9c67a7591924dc874f350913e4db4 # main
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
